language: node_js
node_js:
- '6'
- '8'
- '10'
- '11'

services: mongodb

deploy:
  provider: npm
  email: refack
  api_key: $NPM_REFACK_PUBLISH
  on:
    all_branches: true
    tags: true
    node: '6'
    repo: node4good/formage
